index:
    path: /signUp
    controller: App\Controller\LoginController
    action: insertLogs

createAccount:
    path: /createAccount
    controller: App\Controller\LoginController
    action: goToConnect